version: '3'
services:
  laravel.test:
    # Use codespace integration
    environment:
      # For GitHub Codespaces - ensure ports are exposed
      GITHUB_CODESPACE_PORT_FORWARDING_DOMAIN: "${GITHUB_CODESPACE_PORT_FORWARDING_DOMAIN:-localhost}"

    # Add VS Code integration
    volumes:
      - ~/.gitconfig:/home/sail/.gitconfig:cached
      - vscode-extensions:/home/sail/.vscode-server/extensions
      - vscode-extensions-insiders:/home/sail/.vscode-server-insiders/extensions

    # Add labels for GitHub Codespaces
    labels:
      com.github.codespaces.service: "true"

volumes:
  vscode-extensions:
    driver: local
  vscode-extensions-insiders:
    driver: local
